### ISSUE TITLE
`Data.String.Extra` import needed for using `join`

### ISSUE THREAD

**Issue by andreiburdusa** [octeep/idris2-http#1]
The function `join` used [here](https://github.com/octeep/idris2-http/blob/7afdce354be2a5eddef843b99c775d7939e94253/src/Network/HTTP/Header.idr#L122) is not recognized by the compiler. The following error is raised:
```While processing right hand side of header_write_value. Can't find an implementation for Monad ?m.```

I found that importing `Data.String.Extra` solves the problem. I can open a pull request if you agree.

**Comment by ghost** [comment]
Again thanks for pointing it out. Any PRs are welcome.
