### ISSUE TITLE
[ totality ] Fails to build with latest Idris2 HEAD

### ISSUE THREAD

**Issue by stefan-hoeck** [octeep/idris2-http#4]
Please see the following discussion on [discord](https://discord.com/channels/827106007712661524/827109161857712128/1072807220108079104).

I don't know how to best fix the issue at hand, because `Stream` itself seems not to be total (not strictly positive).

**Comment by ghost** [comment]
Do you mind pinging me in discord so I can locate the discussion? The link doesn't work for me.

**Comment by stefan-hoeck** [comment]
Please note that, in order to get the pack collection to build again, I am going to temporarily remove `http` from it by commenting out its entry in `HEAD.db`. Once this issue has been resolved, you can just submit a PR to [pack-db](https://github.com/stefan-hoeck/idris2-pack-db) where you uncomment its entry in `collections/HEAD.db`.

**Comment by NickSeagull** [comment]
Hey, I'm hitting this too, what would be the way to try fixing this?
